# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Main crate dependencies
  - package-ecosystem: "cargo" # See documentation for possible values
    labels: ["C-Dependencies"]
    directory: "/" # Location of main package manifest
    target-branch: "main"
    schedule:
      interval: "daily"

# INTERNAL CRATES DEPENDABOT CHECKS:
# (Fix issue #57)

  - package-ecosystem: "cargo"
    directory: "/bedrock" # Location of the facade crate "bedrock"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/auth" # Location of internal crate "auth"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/form" # Location of internal crate "form"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/level" # Location of internal crate "level"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/macros" # Location of internal crate "macros"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/network" # Location of internal crate "network"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/protocol" # Location of internal crate "protocol"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/protocol_core" # Location of internal crate "protocol_core"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/shared" # Location of internal crate "shared"
    target-branch: "main"
    schedule:
      interval: "daily"
